/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafegoPagoRouteImport } from './routes/trafego-pago'
import { Route as SobreAAceleriqRouteImport } from './routes/sobre-a-aceleriq'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CriacaoDeSitesRouteImport } from './routes/criacao-de-sites'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomacaoEIaRouteImport } from './routes/automacao-e-ia'
import { Route as AgenciaDeMarketingDigitalCuritibaRouteImport } from './routes/agencia-de-marketing-digital-curitiba'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBacklinksRouteImport } from './routes/admin.backlinks'

const TrafegoPagoRoute = TrafegoPagoRouteImport.update({
  id: '/trafego-pago',
  path: '/trafego-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreAAceleriqRoute = SobreAAceleriqRouteImport.update({
  id: '/sobre-a-aceleriq',
  path: '/sobre-a-aceleriq',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CriacaoDeSitesRoute = CriacaoDeSitesRouteImport.update({
  id: '/criacao-de-sites',
  path: '/criacao-de-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoEIaRoute = AutomacaoEIaRouteImport.update({
  id: '/automacao-e-ia',
  path: '/automacao-e-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciaDeMarketingDigitalCuritibaRoute =
  AgenciaDeMarketingDigitalCuritibaRouteImport.update({
    id: '/agencia-de-marketing-digital-curitiba',
    path: '/agencia-de-marketing-digital-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminBacklinksRoute = AdminBacklinksRouteImport.update({
  id: '/admin/backlinks',
  path: '/admin/backlinks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencia-de-marketing-digital-curitiba': typeof AgenciaDeMarketingDigitalCuritibaRoute
  '/automacao-e-ia': typeof AutomacaoEIaRoute
  '/blog': typeof BlogRouteWithChildren
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-a-aceleriq': typeof SobreAAceleriqRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencia-de-marketing-digital-curitiba': typeof AgenciaDeMarketingDigitalCuritibaRoute
  '/automacao-e-ia': typeof AutomacaoEIaRoute
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-a-aceleriq': typeof SobreAAceleriqRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencia-de-marketing-digital-curitiba': typeof AgenciaDeMarketingDigitalCuritibaRoute
  '/automacao-e-ia': typeof AutomacaoEIaRoute
  '/blog': typeof BlogRouteWithChildren
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-a-aceleriq': typeof SobreAAceleriqRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/admin/backlinks': typeof AdminBacklinksRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencia-de-marketing-digital-curitiba'
    | '/automacao-e-ia'
    | '/blog'
    | '/criacao-de-sites'
    | '/sitemap.xml'
    | '/sobre-a-aceleriq'
    | '/trafego-pago'
    | '/admin/backlinks'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencia-de-marketing-digital-curitiba'
    | '/automacao-e-ia'
    | '/criacao-de-sites'
    | '/sitemap.xml'
    | '/sobre-a-aceleriq'
    | '/trafego-pago'
    | '/admin/backlinks'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/agencia-de-marketing-digital-curitiba'
    | '/automacao-e-ia'
    | '/blog'
    | '/criacao-de-sites'
    | '/sitemap.xml'
    | '/sobre-a-aceleriq'
    | '/trafego-pago'
    | '/admin/backlinks'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciaDeMarketingDigitalCuritibaRoute: typeof AgenciaDeMarketingDigitalCuritibaRoute
  AutomacaoEIaRoute: typeof AutomacaoEIaRoute
  BlogRoute: typeof BlogRouteWithChildren
  CriacaoDeSitesRoute: typeof CriacaoDeSitesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreAAceleriqRoute: typeof SobreAAceleriqRoute
  TrafegoPagoRoute: typeof TrafegoPagoRoute
  AdminBacklinksRoute: typeof AdminBacklinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trafego-pago': {
      id: '/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/trafego-pago'
      preLoaderRoute: typeof TrafegoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-a-aceleriq': {
      id: '/sobre-a-aceleriq'
      path: '/sobre-a-aceleriq'
      fullPath: '/sobre-a-aceleriq'
      preLoaderRoute: typeof SobreAAceleriqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criacao-de-sites': {
      id: '/criacao-de-sites'
      path: '/criacao-de-sites'
      fullPath: '/criacao-de-sites'
      preLoaderRoute: typeof CriacaoDeSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao-e-ia': {
      id: '/automacao-e-ia'
      path: '/automacao-e-ia'
      fullPath: '/automacao-e-ia'
      preLoaderRoute: typeof AutomacaoEIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencia-de-marketing-digital-curitiba': {
      id: '/agencia-de-marketing-digital-curitiba'
      path: '/agencia-de-marketing-digital-curitiba'
      fullPath: '/agencia-de-marketing-digital-curitiba'
      preLoaderRoute: typeof AgenciaDeMarketingDigitalCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/backlinks': {
      id: '/admin/backlinks'
      path: '/admin/backlinks'
      fullPath: '/admin/backlinks'
      preLoaderRoute: typeof AdminBacklinksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciaDeMarketingDigitalCuritibaRoute:
    AgenciaDeMarketingDigitalCuritibaRoute,
  AutomacaoEIaRoute: AutomacaoEIaRoute,
  BlogRoute: BlogRouteWithChildren,
  CriacaoDeSitesRoute: CriacaoDeSitesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreAAceleriqRoute: SobreAAceleriqRoute,
  TrafegoPagoRoute: TrafegoPagoRoute,
  AdminBacklinksRoute: AdminBacklinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
